### ISSUE TITLE
problem z menu

### ISSUE THREAD

**Issue by rekk-zz** [Jaskier/Atari800Win-PLus#1]
Każdą betę oraz pełną 4.1, którą próbuję odpalić w 640x480 partially, to nie da się skorzystać z menu emulatora. Menu miga, wariuje, w starej wersji tego problemu nie było.

**Comment by Jaskier** [comment]
Jak będzie czas (pewnie jesien 2012) wywalamy całą aktualną obsługę grafiki w tym te stare tryby full screen.
